# NAME: Changhui Youn
# EMAIL: tonyyoun2@gmail.com
# ID: 304207830

default:
	/usr/local/cs/bin/gcc -g -Wall -Wextra lab1a.c -o lab1a

clean:
	rm -f *.o lab1a *.txt *.tar.gz

dist: default
	tar -czf lab1a-304207830.tar.gz lab1a.c Makefile README
