#NAME: Changhui Youn
#EMAIL: tonyyoun2@gmail.com
#ID: 304207830

default: 
	rm -f lab3b
	ln my_lab3b lab3b
	chmod u+x lab3b

clean:
	rm -f lab3b-304207830.tar.gz lab3b

dist:
	tar -czvf lab3b-304207830.tar.gz lab3b.py README Makefile my_lab3b