#NAME: Changhui Youn
#EMAIL: tonyyoun2@gmail.com
#ID: 304207830

default: 
	rm -f lab3b
	ln -s lab3b.py lab3b
	chmod +x lab3b

clean:
	rm -f *.tar.gz lab3b

dist:
	tar -czvf lab3b-304207830.tar.gz lab3b.py README Makefile my_lab3b