# NAME: Changhui Youn
# EMAIL: tonyyoun2@gmail.com
# ID: 304207830

default:
	gcc -g -Wall -Wextra lab3a.c -o lab3a

dist: default
	tar -czvf lab3a-304207830.tar.gz lab3a.c Makefile README ext2_fs.h

clean:
	rm -f *.o lab3a *.txt *.tar.gz *.csv trivial.img