# NAME: Changhui Youn
# EMAIL: tonyyoun2@gmail.com
# ID: 304207830

dist: 
	tar -czf lab4a-304207830.tar.gz my_beaglebone.jpg connected.png \
	copy.png build_run.png git.png Makefile README

clean:
	rm -f *.tar.gz
